#!/bin/sh

DAEMON=wsd_simple_server
PRUDYNT_CONFIG=/etc/prudynt.json
ONVIF_CONFIG=/etc/onvif.json
MOTORS_CONFIG=/etc/motors.json
MOTORS_BIN="/bin/motors"

. /usr/share/common

iface="$(iface_default)"

CAMERA=$(awk -F '=' '/^IMAGE_ID=/ {print $2}' $OS_RELEASE_FILE)

ONVIF_IFACE=$(jct $ONVIF_CONFIG get server.ifs)
DAEMON_ARGS="-i $ONVIF_IFACE -x http://%s/onvif/device_service -m $CAMERA -n thingino -p /run/$DAEMON_SHORT.pid"

json_get_trimmed() {
	jct "$1" get "$2" | tr -d '"\r\n'
}

sync_profile() {
	local tmpfile="$1"
	local stream_id="$2"
	local profile_key="profiles.stream${stream_id}"
	local stream_key="stream${stream_id}"
	local width height endpoint format audio_enabled audio_codec

	width="$(json_get_trimmed "$PRUDYNT_CONFIG" "${stream_key}.width")"
	height="$(json_get_trimmed "$PRUDYNT_CONFIG" "${stream_key}.height")"
	endpoint="$(json_get_trimmed "$PRUDYNT_CONFIG" "${stream_key}.rtsp_endpoint")"
	format="$(json_get_trimmed "$PRUDYNT_CONFIG" "${stream_key}.format")"
	audio_enabled="$(json_get_trimmed "$PRUDYNT_CONFIG" "${stream_key}.audio_enabled")"
	audio_codec="$(json_get_trimmed "$PRUDYNT_CONFIG" "audio.input_format")"

	[ -n "$width" ] && jct "$tmpfile" set "${profile_key}.width" "$width"
	[ -n "$height" ] && jct "$tmpfile" set "${profile_key}.height" "$height"
	[ -n "$format" ] && jct "$tmpfile" set "${profile_key}.type" "$format"
	[ -n "$endpoint" ] && jct "$tmpfile" set "${profile_key}.url" "rtsp://%s/$endpoint"

	jct "$tmpfile" set "${profile_key}.name" "Profile_${stream_id}"
	jct "$tmpfile" set "${profile_key}.snapurl" "http://%s/image.jpg"

	if [ "$audio_enabled" = "true" ] && [ -n "$audio_codec" ]; then
		jct "$tmpfile" set "${profile_key}.audio_encoder" "$audio_codec"
		jct "$tmpfile" set "${profile_key}.audio_decoder" "$audio_codec"
	fi
}

start() {
	echo_title "Starting ONVIF discovery"

	if ! is_gateway_reachable; then
		echo_error "Disabled"
		exit 1
	fi

	start_daemon

	tmpfile="$(mktemp -u).json"
	echo '{}' > $tmpfile
	jct $tmpfile set camera.manufacturer "Thingino"
	jct $tmpfile set camera.model "$CAMERA"
	jct $tmpfile set camera.hardware_id "ingenic_$SOC_MODEL"
	jct $tmpfile set camera.serial_num "$(fw_printenv -n ethaddr | sed 's/://g' | tr -d "\n")"
	jct $tmpfile set camera.firmware_ver "$(awk -F'[=,"]' '/^BUILD_ID/{print $3 $4}' /etc/os-release | tr -d "\n")"
	jct $tmpfile set server.ifs $iface
	jct $tmpfile set server.username $(jct $PRUDYNT_CONFIG get rtsp.username)
	jct $tmpfile set server.password $(jct $PRUDYNT_CONFIG get rtsp.password)
	sync_profile "$tmpfile" 0
	sync_profile "$tmpfile" 1

	# conditional PTZ config
	if [ -f "$MOTORS_BIN" ]; then
		steps_pan=$(jct $MOTORS_CONFIG get motors.steps_pan | tr -d "\n")
		steps_tilt=$(jct $MOTORS_CONFIG get motors.steps_tilt | tr -d "\n")

		jct $tmpfile set ptz.enable 1
		jct $tmpfile set ptz.max_step_x "$steps_pan"
		jct $tmpfile set ptz.max_step_y "$steps_tilt"
	else
		jct $tmpfile set ptz.enable 0
	fi
	jct $ONVIF_CONFIG import $tmpfile
	rm -f $tmpfile
}

stop() {
	echo_title "Stopping ONVIF discovery"

	stop_daemon
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
